### ISSUE TITLE
Cannot install from pypi

### ISSUE THREAD

**Issue by jalanb** [khilnani/webpagetest.py#1]
Runnning on OSX with python 2.7:
```
$  pip install webpagetest
Collecting webpagetest
  Downloading webpagetest-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gl/4224mjvs3216zl7qn81_vdm80000gn/T/pip-build-b87scgae/webpagetest/setup.py", line 6, in <module>
        readme = open('README.md', 'r').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by joshkremer** [comment]
I have the same issue

**Comment by vdyshlevyi** [comment]
@jalanb @joshkremer try to install from repo, not from pypi.
`pip install git+https://github.com/khilnani/webpagetest.py@master`
